[package]
name = "ext-biscuit-php"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
description = "PHP wrapper for Biscuit authorization tokens"

[dependencies]
cargo-php = "*"
ext-php-rs = "0.8"

[lib]
name = "ext_biscuit_php"
crate-type = ["cdylib"]
